#1219 Fix for missing request in JWTGuard
tymondesigns/jwt-auth pull request #1223
Opened 2017-06-22 21:38 UTC by michielpeeters

Fixed JWTGuard when it tries to parse the authorization header

2017-06-22 21:46 UTC, tymondesigns requested changes

2017-06-22 21:46 UTC, tymondesigns commented on src/JWTGuard.php
>          if ($this->jwt->getToken() &&
It would be better to change it to 
```php
if ($this->jwt->setRequest($this->request)->getToken() && // etc
```

2017-06-22 21:50 UTC, michielpeeters commented on src/JWTGuard.php
>          if ($this->jwt->getToken() &&
Agree, I have it changed in a new commit :-)

2017-06-22 21:53 UTC, tymondesigns commented
Just need to update tests and fix style and then I'm happy to merge this

2017-06-24 10:23 UTC, tymondesigns commented
@michielpeeters Are you comfortable tweaking the tests for this?

2017-07-06 18:11 UTC, tymondesigns commented
#1243 now implements this.

Thanks for the effort @michielpeeters

2017-07-06 18:11 UTC, closed without merging